SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[mapRegionJumps](
	[fromRegionID] [int] NOT NULL,
	[toRegionID] [int] NOT NULL,
 CONSTRAINT [mapRegionJumps_PK] PRIMARY KEY CLUSTERED 
(
	[fromRegionID] ASC,
	[toRegionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]