//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.SDEToSQL.Importers.YamlToSQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YamlFilesConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YamlFilesConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.SDEToSQL.Importers.YamlToSQL.YamlFilesConstants", typeof(YamlFilesConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blueprints.yaml.
        /// </summary>
        internal static string Blueprints {
            get {
                return ResourceManager.GetString("Blueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categoryIDs.yaml.
        /// </summary>
        internal static string CategoryIDs {
            get {
                return ResourceManager.GetString("CategoryIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificates.yaml.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphicIDs.yaml.
        /// </summary>
        internal static string GraphicsIDs {
            get {
                return ResourceManager.GetString("GraphicsIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groupIDs.yaml.
        /// </summary>
        internal static string GroupIDs {
            get {
                return ResourceManager.GetString("GroupIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iconIDs.yaml.
        /// </summary>
        internal static string IconIDS {
            get {
                return ResourceManager.GetString("IconIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skinLicenses.yaml.
        /// </summary>
        internal static string SkinLicenses {
            get {
                return ResourceManager.GetString("SkinLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skinMaterials.yaml.
        /// </summary>
        internal static string SkinMaterials {
            get {
                return ResourceManager.GetString("SkinMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skins.yaml.
        /// </summary>
        internal static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeIDs.yaml.
        /// </summary>
        internal static string TypeIDs {
            get {
                return ResourceManager.GetString("TypeIDs", resourceCulture);
            }
        }
    }
}
