//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///      &lt;xsl:copy&gt;
        ///          &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///      &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Rowsets are transformed into something else--&gt;
        ///  &lt;xsl:template match [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RowsetsXSLT {
            get {
                return ResourceManager.GetString("RowsetsXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Root --&gt;
        ///  &lt;xsl:template match=&quot;logindata2&quot;&gt;
        ///    &lt;xsl:element name=&quot;OldSettings&quot;&gt;
        ///      &lt;xsl:element name=&quot;accounts&quot;&gt;
        ///        &lt;xsl:for-each select=&quot;Accounts/AccountDetails&quot;&gt;
        ///          &lt;xsl:call-template name=&quot;account&quot;/&gt;
        ///        &lt;/xsl:for-each&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsAndPlanImport {
            get {
                return ResourceManager.GetString("SettingsAndPlanImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:template match=&quot;outputCharacter&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;
        ///          Character Sheet :: &lt;xsl:value-of select=&quot;@name&quot;/&gt;
        ///        &lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;table&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;
        ///              &lt;xsl:element name=&quot;img&quot;&gt;
        ///                &lt;xsl:attribute name=&quot;src&quot;&gt;
        ///                  http://img.eve.is/serv.asp?s=256&amp;amp;c=&lt;xsl: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtmlXslt {
            get {
                return ResourceManager.GetString("XmlToHtmlXslt", resourceCulture);
            }
        }
    }
}
