//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.CloudStorageServices.GoogleDrive {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class GoogleDriveCloudStorageServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GoogleDriveCloudStorageServiceSettings defaultInstance = ((GoogleDriveCloudStorageServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GoogleDriveCloudStorageServiceSettings())));
        
        public static GoogleDriveCloudStorageServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GlgKCJmzGR1BhIyLTLd/GRGJuNRpb4bYk/dsVKiuhMycsTeeromr36d8LSx020rBf2kerBtbqQL2RTf5l" +
            "Q1fNAzZvwNn8KIBGWx0FjEW7vE=")]
        public string AppKey {
            get {
                return ((string)(this["AppKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+rvzyujyHEmSRX3v7PKAYvI2/K2LjWCJxuNAmJKAmxQ=")]
        public string AppSecret {
            get {
                return ((string)(this["AppSecret"]));
            }
        }
    }
}
