/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCharactersCharacterIdBookmarks200Ok :  IEquatable<GetCharactersCharacterIdBookmarks200Ok>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdBookmarks200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCharactersCharacterIdBookmarks200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdBookmarks200Ok" /> class.
        /// </summary>
        /// <param name="BookmarkId">bookmark_id integer (required).</param>
        /// <param name="CreateDate">create_date string (required).</param>
        /// <param name="CreatorId">creator_id integer (required).</param>
        /// <param name="FolderId">folder_id integer.</param>
        /// <param name="Memo">memo string (required).</param>
        /// <param name="Note">note string (required).</param>
        /// <param name="OwnerId">owner_id integer (required).</param>
        /// <param name="Target">Target.</param>
        public GetCharactersCharacterIdBookmarks200Ok(long? BookmarkId = default(long?), DateTime? CreateDate = default(DateTime?), int? CreatorId = default(int?), int? FolderId = default(int?), string Memo = default(string), string Note = default(string), int? OwnerId = default(int?), GetCharactersCharacterIdBookmarksTarget Target = default(GetCharactersCharacterIdBookmarksTarget))
        {
            // to ensure "BookmarkId" is required (not null)
            if (BookmarkId == null)
            {
                throw new InvalidDataException("BookmarkId is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.BookmarkId = BookmarkId;
            }
            // to ensure "CreateDate" is required (not null)
            if (CreateDate == null)
            {
                throw new InvalidDataException("CreateDate is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.CreateDate = CreateDate;
            }
            // to ensure "CreatorId" is required (not null)
            if (CreatorId == null)
            {
                throw new InvalidDataException("CreatorId is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.CreatorId = CreatorId;
            }
            // to ensure "Memo" is required (not null)
            if (Memo == null)
            {
                throw new InvalidDataException("Memo is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.Memo = Memo;
            }
            // to ensure "Note" is required (not null)
            if (Note == null)
            {
                throw new InvalidDataException("Note is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.Note = Note;
            }
            // to ensure "OwnerId" is required (not null)
            if (OwnerId == null)
            {
                throw new InvalidDataException("OwnerId is a required property for GetCharactersCharacterIdBookmarks200Ok and cannot be null");
            }
            else
            {
                this.OwnerId = OwnerId;
            }
            this.FolderId = FolderId;
            this.Target = Target;
        }
        
        /// <summary>
        /// bookmark_id integer
        /// </summary>
        /// <value>bookmark_id integer</value>
        [DataMember(Name="bookmark_id", EmitDefaultValue=false)]
        public long? BookmarkId { get; set; }

        /// <summary>
        /// create_date string
        /// </summary>
        /// <value>create_date string</value>
        [DataMember(Name="create_date", EmitDefaultValue=false)]
        public DateTime? CreateDate { get; set; }

        /// <summary>
        /// creator_id integer
        /// </summary>
        /// <value>creator_id integer</value>
        [DataMember(Name="creator_id", EmitDefaultValue=false)]
        public int? CreatorId { get; set; }

        /// <summary>
        /// folder_id integer
        /// </summary>
        /// <value>folder_id integer</value>
        [DataMember(Name="folder_id", EmitDefaultValue=false)]
        public int? FolderId { get; set; }

        /// <summary>
        /// memo string
        /// </summary>
        /// <value>memo string</value>
        [DataMember(Name="memo", EmitDefaultValue=false)]
        public string Memo { get; set; }

        /// <summary>
        /// note string
        /// </summary>
        /// <value>note string</value>
        [DataMember(Name="note", EmitDefaultValue=false)]
        public string Note { get; set; }

        /// <summary>
        /// owner_id integer
        /// </summary>
        /// <value>owner_id integer</value>
        [DataMember(Name="owner_id", EmitDefaultValue=false)]
        public int? OwnerId { get; set; }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [DataMember(Name="target", EmitDefaultValue=false)]
        public GetCharactersCharacterIdBookmarksTarget Target { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCharactersCharacterIdBookmarks200Ok {\n");
            sb.Append("  BookmarkId: ").Append(BookmarkId).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  CreatorId: ").Append(CreatorId).Append("\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCharactersCharacterIdBookmarks200Ok);
        }

        /// <summary>
        /// Returns true if GetCharactersCharacterIdBookmarks200Ok instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCharactersCharacterIdBookmarks200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCharactersCharacterIdBookmarks200Ok input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BookmarkId == input.BookmarkId ||
                    (this.BookmarkId != null &&
                    this.BookmarkId.Equals(input.BookmarkId))
                ) && 
                (
                    this.CreateDate == input.CreateDate ||
                    (this.CreateDate != null &&
                    this.CreateDate.Equals(input.CreateDate))
                ) && 
                (
                    this.CreatorId == input.CreatorId ||
                    (this.CreatorId != null &&
                    this.CreatorId.Equals(input.CreatorId))
                ) && 
                (
                    this.FolderId == input.FolderId ||
                    (this.FolderId != null &&
                    this.FolderId.Equals(input.FolderId))
                ) && 
                (
                    this.Memo == input.Memo ||
                    (this.Memo != null &&
                    this.Memo.Equals(input.Memo))
                ) && 
                (
                    this.Note == input.Note ||
                    (this.Note != null &&
                    this.Note.Equals(input.Note))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.Target == input.Target ||
                    (this.Target != null &&
                    this.Target.Equals(input.Target))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BookmarkId != null)
                    hashCode = hashCode * 59 + this.BookmarkId.GetHashCode();
                if (this.CreateDate != null)
                    hashCode = hashCode * 59 + this.CreateDate.GetHashCode();
                if (this.CreatorId != null)
                    hashCode = hashCode * 59 + this.CreatorId.GetHashCode();
                if (this.FolderId != null)
                    hashCode = hashCode * 59 + this.FolderId.GetHashCode();
                if (this.Memo != null)
                    hashCode = hashCode * 59 + this.Memo.GetHashCode();
                if (this.Note != null)
                    hashCode = hashCode * 59 + this.Note.GetHashCode();
                if (this.OwnerId != null)
                    hashCode = hashCode * 59 + this.OwnerId.GetHashCode();
                if (this.Target != null)
                    hashCode = hashCode * 59 + this.Target.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
