//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.XmlGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dgmTraits
    {
        public int traitID { get; set; }
        public string bonusText { get; set; }
        public Nullable<byte> unitID { get; set; }
    }
}
