//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.XmlGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EveStaticDataEntities : DbContext
    {
        public EveStaticDataEntities()
            : base("name=EveStaticDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agtAgents> agtAgents { get; set; }
        public virtual DbSet<agtAgentTypes> agtAgentTypes { get; set; }
        public virtual DbSet<agtResearchAgents> agtResearchAgents { get; set; }
        public virtual DbSet<chrAncestries> chrAncestries { get; set; }
        public virtual DbSet<chrAttributes> chrAttributes { get; set; }
        public virtual DbSet<chrBloodlines> chrBloodlines { get; set; }
        public virtual DbSet<chrFactions> chrFactions { get; set; }
        public virtual DbSet<chrRaces> chrRaces { get; set; }
        public virtual DbSet<crpActivities> crpActivities { get; set; }
        public virtual DbSet<crpNPCCorporationDivisions> crpNPCCorporationDivisions { get; set; }
        public virtual DbSet<crpNPCCorporationResearchFields> crpNPCCorporationResearchFields { get; set; }
        public virtual DbSet<crpNPCCorporations> crpNPCCorporations { get; set; }
        public virtual DbSet<crpNPCCorporationTrades> crpNPCCorporationTrades { get; set; }
        public virtual DbSet<crpNPCDivisions> crpNPCDivisions { get; set; }
        public virtual DbSet<crtCertificates> crtCertificates { get; set; }
        public virtual DbSet<crtClasses> crtClasses { get; set; }
        public virtual DbSet<crtRecommendations> crtRecommendations { get; set; }
        public virtual DbSet<crtRelationships> crtRelationships { get; set; }
        public virtual DbSet<dgmAttributeCategories> dgmAttributeCategories { get; set; }
        public virtual DbSet<dgmAttributeTypes> dgmAttributeTypes { get; set; }
        public virtual DbSet<dgmEffects> dgmEffects { get; set; }
        public virtual DbSet<dgmTypeAttributes> dgmTypeAttributes { get; set; }
        public virtual DbSet<dgmTypeEffects> dgmTypeEffects { get; set; }
        public virtual DbSet<eveGraphics> eveGraphics { get; set; }
        public virtual DbSet<eveIcons> eveIcons { get; set; }
        public virtual DbSet<eveUnits> eveUnits { get; set; }
        public virtual DbSet<invBlueprintTypes> invBlueprintTypes { get; set; }
        public virtual DbSet<invCategories> invCategories { get; set; }
        public virtual DbSet<invContrabandTypes> invContrabandTypes { get; set; }
        public virtual DbSet<invControlTowerResourcePurposes> invControlTowerResourcePurposes { get; set; }
        public virtual DbSet<invControlTowerResources> invControlTowerResources { get; set; }
        public virtual DbSet<invFlags> invFlags { get; set; }
        public virtual DbSet<invGroups> invGroups { get; set; }
        public virtual DbSet<invItems> invItems { get; set; }
        public virtual DbSet<invMarketGroups> invMarketGroups { get; set; }
        public virtual DbSet<invMetaGroups> invMetaGroups { get; set; }
        public virtual DbSet<invMetaTypes> invMetaTypes { get; set; }
        public virtual DbSet<invNames> invNames { get; set; }
        public virtual DbSet<invPositions> invPositions { get; set; }
        public virtual DbSet<invTypeMaterials> invTypeMaterials { get; set; }
        public virtual DbSet<invTypeReactions> invTypeReactions { get; set; }
        public virtual DbSet<invTypes> invTypes { get; set; }
        public virtual DbSet<invUniqueNames> invUniqueNames { get; set; }
        public virtual DbSet<mapCelestialStatistics> mapCelestialStatistics { get; set; }
        public virtual DbSet<mapConstellationJumps> mapConstellationJumps { get; set; }
        public virtual DbSet<mapConstellations> mapConstellations { get; set; }
        public virtual DbSet<mapDenormalize> mapDenormalize { get; set; }
        public virtual DbSet<mapJumps> mapJumps { get; set; }
        public virtual DbSet<mapLandmarks> mapLandmarks { get; set; }
        public virtual DbSet<mapLocationScenes> mapLocationScenes { get; set; }
        public virtual DbSet<mapLocationWormholeClasses> mapLocationWormholeClasses { get; set; }
        public virtual DbSet<mapRegionJumps> mapRegionJumps { get; set; }
        public virtual DbSet<mapRegions> mapRegions { get; set; }
        public virtual DbSet<mapSolarSystemJumps> mapSolarSystemJumps { get; set; }
        public virtual DbSet<mapSolarSystems> mapSolarSystems { get; set; }
        public virtual DbSet<mapUniverse> mapUniverse { get; set; }
        public virtual DbSet<planetSchematics> planetSchematics { get; set; }
        public virtual DbSet<planetSchematicsPinMap> planetSchematicsPinMap { get; set; }
        public virtual DbSet<planetSchematicsTypeMap> planetSchematicsTypeMap { get; set; }
        public virtual DbSet<ramActivities> ramActivities { get; set; }
        public virtual DbSet<ramAssemblyLines> ramAssemblyLines { get; set; }
        public virtual DbSet<ramAssemblyLineStations> ramAssemblyLineStations { get; set; }
        public virtual DbSet<ramAssemblyLineTypeDetailPerCategory> ramAssemblyLineTypeDetailPerCategory { get; set; }
        public virtual DbSet<ramAssemblyLineTypeDetailPerGroup> ramAssemblyLineTypeDetailPerGroup { get; set; }
        public virtual DbSet<ramAssemblyLineTypes> ramAssemblyLineTypes { get; set; }
        public virtual DbSet<ramInstallationTypeContents> ramInstallationTypeContents { get; set; }
        public virtual DbSet<ramTypeRequirements> ramTypeRequirements { get; set; }
        public virtual DbSet<staOperations> staOperations { get; set; }
        public virtual DbSet<staOperationServices> staOperationServices { get; set; }
        public virtual DbSet<staServices> staServices { get; set; }
        public virtual DbSet<staStations> staStations { get; set; }
        public virtual DbSet<staStationTypes> staStationTypes { get; set; }
        public virtual DbSet<translationTables> translationTables { get; set; }
        public virtual DbSet<trnTranslationColumns> trnTranslationColumns { get; set; }
        public virtual DbSet<trnTranslationLanguages> trnTranslationLanguages { get; set; }
        public virtual DbSet<trnTranslations> trnTranslations { get; set; }
        public virtual DbSet<warCombatZones> warCombatZones { get; set; }
        public virtual DbSet<warCombatZoneSystems> warCombatZoneSystems { get; set; }
        public virtual DbSet<dgmMasteries> dgmMasteries { get; set; }
        public virtual DbSet<dgmTraits> dgmTraits { get; set; }
        public virtual DbSet<dgmTypeMasteries> dgmTypeMasteries { get; set; }
        public virtual DbSet<dgmTypeTraits> dgmTypeTraits { get; set; }
    }
}
