//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.XmlGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMarketGroups
    {
        public int marketGroupID { get; set; }
        public Nullable<int> parentGroupID { get; set; }
        public string marketGroupName { get; set; }
        public string description { get; set; }
        public Nullable<int> iconID { get; set; }
        public Nullable<bool> hasTypes { get; set; }
    }
}
