//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.XmlGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnTranslationColumns
    {
        public Nullable<short> tcGroupID { get; set; }
        public short tcID { get; set; }
        public string tableName { get; set; }
        public string columnName { get; set; }
        public string masterID { get; set; }
    }
}
