//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.SDEExternalsToSql.SQLiteToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapRegionJumps
    {
        public long fromRegionID { get; set; }
        public long toRegionID { get; set; }
    }
}
