//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.SDEExternalsToSql.SQLiteToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapSolarSystemJumps
    {
        public Nullable<long> fromRegionID { get; set; }
        public Nullable<long> fromConstellationID { get; set; }
        public long fromSolarSystemID { get; set; }
        public long toSolarSystemID { get; set; }
        public Nullable<long> toConstellationID { get; set; }
        public Nullable<long> toRegionID { get; set; }
    }
}
