//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetworkConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.NetworkConstants", typeof(NetworkConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/AccountBalance.xml.aspx.
        /// </summary>
        public static string APIAccountBalance {
            get {
                return ResourceManager.GetString("APIAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/AccountStatus.xml.aspx.
        /// </summary>
        public static string APIAccountStatus {
            get {
                return ResourceManager.GetString("APIAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/AllianceList.xml.aspx.
        /// </summary>
        public static string APIAllianceList {
            get {
                return ResourceManager.GetString("APIAllianceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/APIKeyInfo.xml.aspx.
        /// </summary>
        public static string APIAPIKeyInfo {
            get {
                return ResourceManager.GetString("APIAPIKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/AssetList.xml.aspx.
        /// </summary>
        public static string APIAssetList {
            get {
                return ResourceManager.GetString("APIAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.eveonline.com.
        /// </summary>
        public static string APIBase {
            get {
                return ResourceManager.GetString("APIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/CalendarEventAttendees.xml.aspx.
        /// </summary>
        public static string APICalendarEventAttendees {
            get {
                return ResourceManager.GetString("APICalendarEventAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/CallList.xml.aspx.
        /// </summary>
        public static string APICallList {
            get {
                return ResourceManager.GetString("APICallList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/CertificateTree.xml.aspx.
        /// </summary>
        public static string APICertificateTree {
            get {
                return ResourceManager.GetString("APICertificateTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/CharacterID.xml.aspx.
        /// </summary>
        public static string APICharacterID {
            get {
                return ResourceManager.GetString("APICharacterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/CharacterInfo.xml.aspx.
        /// </summary>
        public static string APICharacterInfo {
            get {
                return ResourceManager.GetString("APICharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/Characters.xml.aspx.
        /// </summary>
        public static string APICharacterList {
            get {
                return ResourceManager.GetString("APICharacterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/CharacterName.xml.aspx.
        /// </summary>
        public static string APICharacterName {
            get {
                return ResourceManager.GetString("APICharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/CharacterSheet.xml.aspx.
        /// </summary>
        public static string APICharacterSheet {
            get {
                return ResourceManager.GetString("APICharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/ConquerableStationList.xml.aspx.
        /// </summary>
        public static string APIConquerableStationList {
            get {
                return ResourceManager.GetString("APIConquerableStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContactList.xml.aspx.
        /// </summary>
        public static string APIContactList {
            get {
                return ResourceManager.GetString("APIContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContactNotifications.xml.aspx.
        /// </summary>
        public static string APIContactNotifications {
            get {
                return ResourceManager.GetString("APIContactNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContractBids.xml.aspx.
        /// </summary>
        public static string APIContractBids {
            get {
                return ResourceManager.GetString("APIContractBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContractItems.xml.aspx.
        /// </summary>
        public static string APIContractItems {
            get {
                return ResourceManager.GetString("APIContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Contracts.xml.aspx.
        /// </summary>
        public static string APIContracts {
            get {
                return ResourceManager.GetString("APIContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/AccountBalance.xml.aspx.
        /// </summary>
        public static string APICorporationAccountBalance {
            get {
                return ResourceManager.GetString("APICorporationAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/AssetList.xml.aspx.
        /// </summary>
        public static string APICorporationAssetList {
            get {
                return ResourceManager.GetString("APICorporationAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/ContactList.xml.aspx.
        /// </summary>
        public static string APICorporationContactList {
            get {
                return ResourceManager.GetString("APICorporationContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/ContainerLog.xml.aspx.
        /// </summary>
        public static string APICorporationContainerLog {
            get {
                return ResourceManager.GetString("APICorporationContainerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/ContractBids.xml.aspx.
        /// </summary>
        public static string APICorporationContractBids {
            get {
                return ResourceManager.GetString("APICorporationContractBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/ContractItems.xml.aspx.
        /// </summary>
        public static string APICorporationContractItems {
            get {
                return ResourceManager.GetString("APICorporationContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Contracts.xml.aspx.
        /// </summary>
        public static string APICorporationContracts {
            get {
                return ResourceManager.GetString("APICorporationContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/FacWarStats.xml.aspx.
        /// </summary>
        public static string APICorporationFactionalWarfareStats {
            get {
                return ResourceManager.GetString("APICorporationFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/IndustryJobs.xml.aspx.
        /// </summary>
        public static string APICorporationIndustryJobs {
            get {
                return ResourceManager.GetString("APICorporationIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Killlog.xml.aspx.
        /// </summary>
        public static string APICorporationKillLog {
            get {
                return ResourceManager.GetString("APICorporationKillLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Locations.xml.aspx.
        /// </summary>
        public static string APICorporationLocations {
            get {
                return ResourceManager.GetString("APICorporationLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MarketOrders.xml.aspx.
        /// </summary>
        public static string APICorporationMarketOrders {
            get {
                return ResourceManager.GetString("APICorporationMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Medals.xml.aspx.
        /// </summary>
        public static string APICorporationMedals {
            get {
                return ResourceManager.GetString("APICorporationMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MemberMedals.xml.aspx.
        /// </summary>
        public static string APICorporationMemberMedals {
            get {
                return ResourceManager.GetString("APICorporationMemberMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MemberSecurity.xml.aspx.
        /// </summary>
        public static string APICorporationMemberSecurity {
            get {
                return ResourceManager.GetString("APICorporationMemberSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MemberSecurityLog.xml.aspx.
        /// </summary>
        public static string APICorporationMemberSecurityLog {
            get {
                return ResourceManager.GetString("APICorporationMemberSecurityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MemberTracking.xml.aspx.
        /// </summary>
        public static string APICorporationMemberTrackingExtended {
            get {
                return ResourceManager.GetString("APICorporationMemberTrackingExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MemberTracking.xml.aspx.
        /// </summary>
        public static string APICorporationMemberTrackingLimited {
            get {
                return ResourceManager.GetString("APICorporationMemberTrackingLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/OutpostList.xml.aspx.
        /// </summary>
        public static string APICorporationOutpostList {
            get {
                return ResourceManager.GetString("APICorporationOutpostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/OutpostServiceDetail.xml.aspx.
        /// </summary>
        public static string APICorporationOutpostServiceDetail {
            get {
                return ResourceManager.GetString("APICorporationOutpostServiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Shareholders.xml.aspx.
        /// </summary>
        public static string APICorporationShareholders {
            get {
                return ResourceManager.GetString("APICorporationShareholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/CorporationSheet.xml.aspx.
        /// </summary>
        public static string APICorporationSheet {
            get {
                return ResourceManager.GetString("APICorporationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Standings.xml.aspx.
        /// </summary>
        public static string APICorporationStandings {
            get {
                return ResourceManager.GetString("APICorporationStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/StarbaseDetail.xml.aspx.
        /// </summary>
        public static string APICorporationStarbaseDetails {
            get {
                return ResourceManager.GetString("APICorporationStarbaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/StarbaseList.xml.aspx.
        /// </summary>
        public static string APICorporationStarbaseList {
            get {
                return ResourceManager.GetString("APICorporationStarbaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/Titles.xml.aspx.
        /// </summary>
        public static string APICorporationTitles {
            get {
                return ResourceManager.GetString("APICorporationTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/WalletJournal.xml.aspx.
        /// </summary>
        public static string APICorporationWalletJournal {
            get {
                return ResourceManager.GetString("APICorporationWalletJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/WalletTransactions.xml.aspx.
        /// </summary>
        public static string APICorporationWalletTransactions {
            get {
                return ResourceManager.GetString("APICorporationWalletTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.eveonline.com/api.
        /// </summary>
        public static string APICredentials {
            get {
                return ResourceManager.GetString("APICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.eveonline.com/api/key/activeinstalllinks.
        /// </summary>
        public static string APICredentialsInstallLinks {
            get {
                return ResourceManager.GetString("APICredentialsInstallLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.eveonline.com/api/key/createpredefined/{0}.
        /// </summary>
        public static string APICredentialsPredefined {
            get {
                return ResourceManager.GetString("APICredentialsPredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.eveonline.com/api/key/update/{0}.
        /// </summary>
        public static string APICredentialsUpdate {
            get {
                return ResourceManager.GetString("APICredentialsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/ErrorList.xml.aspx.
        /// </summary>
        public static string APIErrorList {
            get {
                return ResourceManager.GetString("APIErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/FacWarStats.xml.aspx.
        /// </summary>
        public static string APIEVEFactionalWarfareStats {
            get {
                return ResourceManager.GetString("APIEVEFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/FacWarTopStats.xml.aspx.
        /// </summary>
        public static string APIEVEFactionalWarfareTopStats {
            get {
                return ResourceManager.GetString("APIEVEFactionalWarfareTopStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/FacWarStats.xml.aspx.
        /// </summary>
        public static string APIFactionalWarfareStats {
            get {
                return ResourceManager.GetString("APIFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /map/FacWarSystems.xml.aspx.
        /// </summary>
        public static string APIFactionalWarfareSystems {
            get {
                return ResourceManager.GetString("APIFactionalWarfareSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/IndustryJobs.xml.aspx.
        /// </summary>
        public static string APIIndustryJobs {
            get {
                return ResourceManager.GetString("APIIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /map/Jumps.xml.aspx.
        /// </summary>
        public static string APIJumps {
            get {
                return ResourceManager.GetString("APIJumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Killlog.xml.aspx.
        /// </summary>
        public static string APIKillLog {
            get {
                return ResourceManager.GetString("APIKillLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /map/Kills.xml.aspx.
        /// </summary>
        public static string APIKills {
            get {
                return ResourceManager.GetString("APIKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Locations.xml.aspx.
        /// </summary>
        public static string APILocations {
            get {
                return ResourceManager.GetString("APILocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailBodies.xml.aspx.
        /// </summary>
        public static string APIMailBodies {
            get {
                return ResourceManager.GetString("APIMailBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailingLists.xml.aspx.
        /// </summary>
        public static string APIMailingLists {
            get {
                return ResourceManager.GetString("APIMailingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailMessages.xml.aspx.
        /// </summary>
        public static string APIMailMessages {
            get {
                return ResourceManager.GetString("APIMailMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MarketOrders.xml.aspx.
        /// </summary>
        public static string APIMarketOrders {
            get {
                return ResourceManager.GetString("APIMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Medals.xml.aspx.
        /// </summary>
        public static string APIMedals {
            get {
                return ResourceManager.GetString("APIMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Notifications.xml.aspx.
        /// </summary>
        public static string APINotifications {
            get {
                return ResourceManager.GetString("APINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/NotificationTexts.xml.aspx.
        /// </summary>
        public static string APINotificationTexts {
            get {
                return ResourceManager.GetString("APINotificationTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/RefTypes.xml.aspx.
        /// </summary>
        public static string APIRefTypes {
            get {
                return ResourceManager.GetString("APIRefTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Research.xml.aspx.
        /// </summary>
        public static string APIResearchPoints {
            get {
                return ResourceManager.GetString("APIResearchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /server/ServerStatus.xml.aspx.
        /// </summary>
        public static string APIServerStatus {
            get {
                return ResourceManager.GetString("APIServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillInTraining.xml.aspx.
        /// </summary>
        public static string APISkillInTraining {
            get {
                return ResourceManager.GetString("APISkillInTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillQueue.xml.aspx.
        /// </summary>
        public static string APISkillQueue {
            get {
                return ResourceManager.GetString("APISkillQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/SkillTree.xml.aspx.
        /// </summary>
        public static string APISkillTree {
            get {
                return ResourceManager.GetString("APISkillTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /map/Sovereignty.xml.aspx.
        /// </summary>
        public static string APISovereignty {
            get {
                return ResourceManager.GetString("APISovereignty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Standings.xml.aspx.
        /// </summary>
        public static string APIStandings {
            get {
                return ResourceManager.GetString("APIStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://apitest.eveonline.com.
        /// </summary>
        public static string APITestBase {
            get {
                return ResourceManager.GetString("APITestBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/TypeName.xml.aspx.
        /// </summary>
        public static string APITypeName {
            get {
                return ResourceManager.GetString("APITypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/UpcomingCalendarEvents.xml.aspx.
        /// </summary>
        public static string APIUpcomingCalendarEvents {
            get {
                return ResourceManager.GetString("APIUpcomingCalendarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/WalletJournal.xml.aspx.
        /// </summary>
        public static string APIWalletJournal {
            get {
                return ResourceManager.GetString("APIWalletJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/WalletTransactions.xml.aspx.
        /// </summary>
        public static string APIWalletTransactions {
            get {
                return ResourceManager.GetString("APIWalletTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.battleclinic.com/time.php.
        /// </summary>
        public static string BatlleclinicTimeSynch {
            get {
                return ResourceManager.GetString("BatlleclinicTimeSynch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.battleclinic.com.
        /// </summary>
        public static string BattleClinicBase {
            get {
                return ResourceManager.GetString("BattleClinicBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.battleclinic.com/ship_loadout_feed.php?id={0}.
        /// </summary>
        public static string BattleclinicLoadoutDetails {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.battleclinic.com/ship_loadout_feed.php?typeID={0}.
        /// </summary>
        public static string BattleclinicLoadoutsFeed {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.battleclinic.com/index.php/topic,{0}.0.html.
        /// </summary>
        public static string BattleclinicLoadoutTopic {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.battleclinic.com/api_key.php.
        /// </summary>
        public static string BCAPIAccountCredentials {
            get {
                return ResourceManager.GetString("BCAPIAccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.battleclinic.com.
        /// </summary>
        public static string BCAPIBase {
            get {
                return ResourceManager.GetString("BCAPIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/checkAPICredentials.php.
        /// </summary>
        public static string BCAPICheckCredentials {
            get {
                return ResourceManager.GetString("BCAPICheckCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileGet.php.
        /// </summary>
        public static string BCAPIFileGet {
            get {
                return ResourceManager.GetString("BCAPIFileGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileGetByName.php.
        /// </summary>
        public static string BCAPIFileGetByName {
            get {
                return ResourceManager.GetString("BCAPIFileGetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileSave.php.
        /// </summary>
        public static string BCAPIFileSave {
            get {
                return ResourceManager.GetString("BCAPIFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.eveonline.com/AccountManMenu.aspx.
        /// </summary>
        public static string CCPAccountManage {
            get {
                return ResourceManager.GetString("CCPAccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.no-ip.de/{0}/{1}/{2}.png.
        /// </summary>
        public static string CCPIcons {
            get {
                return ResourceManager.GetString("CCPIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/{0}/{1}_{2}.png.
        /// </summary>
        public static string CCPIconsFromImageServer {
            get {
                return ResourceManager.GetString("CCPIconsFromImageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/character/{0}_{1}.jpg.
        /// </summary>
        public static string CCPPortraits {
            get {
                return ResourceManager.GetString("CCPPortraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gate.eveonline.com.
        /// </summary>
        public static string EVEGate {
            get {
                return ResourceManager.GetString("EVEGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Alliance/{0}.
        /// </summary>
        public static string EVEGateAllianceProfile {
            get {
                return ResourceManager.GetString("EVEGateAllianceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        public static string EVEGateCharacterProfile {
            get {
                return ResourceManager.GetString("EVEGateCharacterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Corporation/{0}.
        /// </summary>
        public static string EVEGateCorporationProfile {
            get {
                return ResourceManager.GetString("EVEGateCorporationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeForward/{0}.
        /// </summary>
        public static string EVEGateMailForward {
            get {
                return ResourceManager.GetString("EVEGateMailForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ReadMessage/{0}.
        /// </summary>
        public static string EVEGateMailOpen {
            get {
                return ResourceManager.GetString("EVEGateMailOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeReply/{0}.
        /// </summary>
        public static string EVEGateMailReply {
            get {
                return ResourceManager.GetString("EVEGateMailReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeReplyAll/{0}.
        /// </summary>
        public static string EVEGateMailReplyAll {
            get {
                return ResourceManager.GetString("EVEGateMailReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.battleclinic.com/index.php/How_to_write_an_useful_bug_report_%28EVEMon%29_%3F.
        /// </summary>
        public static string EVEMonBugReport {
            get {
                return ResourceManager.GetString("EVEMonBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.battleclinic.com/index.php#c36.
        /// </summary>
        public static string EVEMonForums {
            get {
                return ResourceManager.GetString("EVEMonForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.battleclinic.com/index.php/Known_problems_%28EVEMon%29.
        /// </summary>
        public static string EVEMonKnownProblems {
            get {
                return ResourceManager.GetString("EVEMonKnownProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemon.battleclinic.com/.
        /// </summary>
        public static string EVEMonMainPage {
            get {
                return ResourceManager.GetString("EVEMonMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/BattleClinic/evemon/wiki/updates/patch.xml.
        /// </summary>
        public static string EVEMonUpdates {
            get {
                return ResourceManager.GetString("EVEMonUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemon.uservoice.com/.
        /// </summary>
        public static string EVEMonUserVoice {
            get {
                return ResourceManager.GetString("EVEMonUserVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/calendar/feeds/default/private/full.
        /// </summary>
        public static string GoogleCalendarURL {
            get {
                return ResourceManager.GetString("GoogleCalendarURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.eveonline.com/bitmaps/character/level.
        /// </summary>
        public static string MyEVELevelImage {
            get {
                return ResourceManager.GetString("MyEVELevelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}.
        /// </summary>
        public static string PostDataBase {
            get {
                return ResourceManager.GetString("PostDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characterID={0}.
        /// </summary>
        public static string PostDataCharacterIDOnly {
            get {
                return ResourceManager.GetString("PostDataCharacterIDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporationID={0}.
        /// </summary>
        public static string PostDataCorporationIDOnly {
            get {
                return ResourceManager.GetString("PostDataCorporationIDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ids={0}.
        /// </summary>
        public static string PostDataIDsOnly {
            get {
                return ResourceManager.GetString("PostDataIDsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to names={0}.
        /// </summary>
        public static string PostDataNamesOnly {
            get {
                return ResourceManager.GetString("PostDataNamesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}&amp;characterID={2}.
        /// </summary>
        public static string PostDataWithCharID {
            get {
                return ResourceManager.GetString("PostDataWithCharID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}&amp;characterID={2}&amp;contractID={3}.
        /// </summary>
        public static string PostDataWithCharIDAndContractID {
            get {
                return ResourceManager.GetString("PostDataWithCharIDAndContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}&amp;characterID={2}&amp;ids={3}.
        /// </summary>
        public static string PostDataWithCharIDAndIDS {
            get {
                return ResourceManager.GetString("PostDataWithCharIDAndIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}&amp;extended=1.
        /// </summary>
        public static string PostDataWithExtendedParameter {
            get {
                return ResourceManager.GetString("PostDataWithExtendedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyID={0}&amp;vCode={1}&amp;itemID={2}.
        /// </summary>
        public static string PostDataWithItemID {
            get {
                return ResourceManager.GetString("PostDataWithItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/BattleClinic/evemon/wiki/emuu/endpoints/endpoints.json.
        /// </summary>
        public static string UploaderEndPoints {
            get {
                return ResourceManager.GetString("UploaderEndPoints", resourceCulture);
            }
        }
    }
}
