//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetworkConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Constants.NetworkConstants", typeof(NetworkConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/EVEMonDevTeam/evemon.
        /// </summary>
        public static string BitBucketBase {
            get {
                return ResourceManager.GetString("BitBucketBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://peterhaneve.github.io/evemon-datafiles/.
        /// </summary>
        public static string BitBucketDatafilesBase {
            get {
                return ResourceManager.GetString("BitBucketDatafilesBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/EVEMonDevTeam/evemon/issues.
        /// </summary>
        public static string BitBucketIssuesBase {
            get {
                return ResourceManager.GetString("BitBucketIssuesBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/EVEMonDevTeam/evemon/wiki.
        /// </summary>
        public static string BitBucketWikiBase {
            get {
                return ResourceManager.GetString("BitBucketWikiBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.eveonline.com/AccountManMenu.aspx.
        /// </summary>
        public static string CCPAccountManage {
            get {
                return ResourceManager.GetString("CCPAccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://peterhaneve.github.io/evemon-esi.
        /// </summary>
        public static string CCPApplicationRegistration {
            get {
                return ResourceManager.GetString("CCPApplicationRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}/{1}_{2}.png.
        /// </summary>
        public static string CCPIconsFromImageServer {
            get {
                return ResourceManager.GetString("CCPIconsFromImageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /character/{0}_{1}.jpg.
        /// </summary>
        public static string CCPPortraits {
            get {
                return ResourceManager.GetString("CCPPortraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/wallet/.
        /// </summary>
        public static string ESIAccountBalance {
            get {
                return ResourceManager.GetString("ESIAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/accountStatus/.
        /// </summary>
        public static string ESIAccountStatus {
            get {
                return ResourceManager.GetString("ESIAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/alliances/.
        /// </summary>
        public static string ESIAllianceList {
            get {
                return ResourceManager.GetString("ESIAllianceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/characters/{0:D}/assets/.
        /// </summary>
        public static string ESIAssetList {
            get {
                return ResourceManager.GetString("ESIAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/attributes/.
        /// </summary>
        public static string ESIAttributes {
            get {
                return ResourceManager.GetString("ESIAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://esi.evetech.net.
        /// </summary>
        public static string ESIBase {
            get {
                return ResourceManager.GetString("ESIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/blueprints/.
        /// </summary>
        public static string ESIBlueprints {
            get {
                return ResourceManager.GetString("ESIBlueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/bookmarks/.
        /// </summary>
        public static string ESIBookmarks {
            get {
                return ResourceManager.GetString("ESIBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/calendar/{1:D}/attendees/.
        /// </summary>
        public static string ESICalendarEventAttendees {
            get {
                return ResourceManager.GetString("ESICalendarEventAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/affiliation/.
        /// </summary>
        public static string ESICharacterAffliation {
            get {
                return ResourceManager.GetString("ESICharacterAffliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/fatigue/.
        /// </summary>
        public static string ESICharacterFatigue {
            get {
                return ResourceManager.GetString("ESICharacterFatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/universe/names/.
        /// </summary>
        public static string ESICharacterName {
            get {
                return ResourceManager.GetString("ESICharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v4/characters/{0:D}/.
        /// </summary>
        public static string ESICharacterSheet {
            get {
                return ResourceManager.GetString("ESICharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v4/characters/{0:D}/skills/.
        /// </summary>
        public static string ESICharacterSkills {
            get {
                return ResourceManager.GetString("ESICharacterSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/chat_channels/.
        /// </summary>
        public static string ESIChatChannels {
            get {
                return ResourceManager.GetString("ESIChatChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/universe/structures/{0}/.
        /// </summary>
        public static string ESICitadelInfo {
            get {
                return ResourceManager.GetString("ESICitadelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/characters/{0:D}/clones/.
        /// </summary>
        public static string ESIClones {
            get {
                return ResourceManager.GetString("ESIClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/contacts/.
        /// </summary>
        public static string ESIContactList {
            get {
                return ResourceManager.GetString("ESIContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/contracts/{1:D}/bids/.
        /// </summary>
        public static string ESIContractBids {
            get {
                return ResourceManager.GetString("ESIContractBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/contracts/{1:D}/items/.
        /// </summary>
        public static string ESIContractItems {
            get {
                return ResourceManager.GetString("ESIContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/contracts/.
        /// </summary>
        public static string ESIContracts {
            get {
                return ResourceManager.GetString("ESIContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/wallets/.
        /// </summary>
        public static string ESICorporationAccountBalance {
            get {
                return ResourceManager.GetString("ESICorporationAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/corporations/{0:D}/assets/.
        /// </summary>
        public static string ESICorporationAssetList {
            get {
                return ResourceManager.GetString("ESICorporationAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/corporations/{0:D}/blueprints/.
        /// </summary>
        public static string ESICorporationBlueprints {
            get {
                return ResourceManager.GetString("ESICorporationBlueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/bookmarks/.
        /// </summary>
        public static string ESICorporationBookmarks {
            get {
                return ResourceManager.GetString("ESICorporationBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/corporations/{0:D}/contacts/.
        /// </summary>
        public static string ESICorporationContactList {
            get {
                return ResourceManager.GetString("ESICorporationContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/corporations/{0:D}/containers/logs/.
        /// </summary>
        public static string ESICorporationContainerLog {
            get {
                return ResourceManager.GetString("ESICorporationContainerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/contracts/{1:D}/bids/.
        /// </summary>
        public static string ESICorporationContractBids {
            get {
                return ResourceManager.GetString("ESICorporationContractBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/contracts/{1:D}/items/.
        /// </summary>
        public static string ESICorporationContractItems {
            get {
                return ResourceManager.GetString("ESICorporationContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/contracts/.
        /// </summary>
        public static string ESICorporationContracts {
            get {
                return ResourceManager.GetString("ESICorporationContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/fw/stats/.
        /// </summary>
        public static string ESICorporationFactionalWarfareStats {
            get {
                return ResourceManager.GetString("ESICorporationFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/industry/jobs/.
        /// </summary>
        public static string ESICorporationIndustryJobs {
            get {
                return ResourceManager.GetString("ESICorporationIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/killmails/recent/.
        /// </summary>
        public static string ESICorporationKillLog {
            get {
                return ResourceManager.GetString("ESICorporationKillLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/corporations/{0:D}/orders/.
        /// </summary>
        public static string ESICorporationMarketOrders {
            get {
                return ResourceManager.GetString("ESICorporationMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/medals/.
        /// </summary>
        public static string ESICorporationMedals {
            get {
                return ResourceManager.GetString("ESICorporationMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/medals/issued/.
        /// </summary>
        public static string ESICorporationMemberMedals {
            get {
                return ResourceManager.GetString("ESICorporationMemberMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/membertracking/.
        /// </summary>
        public static string ESICorporationMemberTracking {
            get {
                return ResourceManager.GetString("ESICorporationMemberTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/outposts/.
        /// </summary>
        public static string ESICorporationOutpostList {
            get {
                return ResourceManager.GetString("ESICorporationOutpostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/outposts/{1:D}/.
        /// </summary>
        public static string ESICorporationOutpostServiceDetail {
            get {
                return ResourceManager.GetString("ESICorporationOutpostServiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/shareholders/.
        /// </summary>
        public static string ESICorporationShareholders {
            get {
                return ResourceManager.GetString("ESICorporationShareholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v4/corporations/{0:D}/.
        /// </summary>
        public static string ESICorporationSheet {
            get {
                return ResourceManager.GetString("ESICorporationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/standings/.
        /// </summary>
        public static string ESICorporationStandings {
            get {
                return ResourceManager.GetString("ESICorporationStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/starbases/{1:D}/.
        /// </summary>
        public static string ESICorporationStarbaseDetails {
            get {
                return ResourceManager.GetString("ESICorporationStarbaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/starbases/.
        /// </summary>
        public static string ESICorporationStarbaseList {
            get {
                return ResourceManager.GetString("ESICorporationStarbaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/titles/.
        /// </summary>
        public static string ESICorporationTitles {
            get {
                return ResourceManager.GetString("ESICorporationTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/corporations/{0:D}/wallets/{1:D}/journal/.
        /// </summary>
        public static string ESICorporationWalletJournal {
            get {
                return ResourceManager.GetString("ESICorporationWalletJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/corporations/{0:D}/wallets/{1:D}/transactions/.
        /// </summary>
        public static string ESICorporationWalletTransactions {
            get {
                return ResourceManager.GetString("ESICorporationWalletTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/corporationhistory/.
        /// </summary>
        public static string ESIEmploymentHistory {
            get {
                return ResourceManager.GetString("ESIEmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/fw/stats/.
        /// </summary>
        public static string ESIEVEFactionalWarfareStats {
            get {
                return ResourceManager.GetString("ESIEVEFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/fw/leaderboards/.
        /// </summary>
        public static string ESIEVEFactionalWarfareTopStats {
            get {
                return ResourceManager.GetString("ESIEVEFactionalWarfareTopStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/fw/stats/.
        /// </summary>
        public static string ESIFactionalWarfareStats {
            get {
                return ResourceManager.GetString("ESIFactionalWarfareStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/fw/systems/.
        /// </summary>
        public static string ESIFactionalWarfareSystems {
            get {
                return ResourceManager.GetString("ESIFactionalWarfareSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/fw/wars/.
        /// </summary>
        public static string ESIFactionWars {
            get {
                return ResourceManager.GetString("ESIFactionWars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/implants/.
        /// </summary>
        public static string ESIImplants {
            get {
                return ResourceManager.GetString("ESIImplants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/industry/jobs/.
        /// </summary>
        public static string ESIIndustryJobs {
            get {
                return ResourceManager.GetString("ESIIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/fatigue/.
        /// </summary>
        public static string ESIJumpFatigue {
            get {
                return ResourceManager.GetString("ESIJumpFatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/universe/system_jumps/.
        /// </summary>
        public static string ESIJumps {
            get {
                return ResourceManager.GetString("ESIJumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/killmails/recent/.
        /// </summary>
        public static string ESIKillLog {
            get {
                return ResourceManager.GetString("ESIKillLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/killmails/{0}/{1}/.
        /// </summary>
        public static string ESIKillMail {
            get {
                return ResourceManager.GetString("ESIKillMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/universe/system_kills/.
        /// </summary>
        public static string ESIKills {
            get {
                return ResourceManager.GetString("ESIKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/location/.
        /// </summary>
        public static string ESILocation {
            get {
                return ResourceManager.GetString("ESILocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/mail/{1:D}/.
        /// </summary>
        public static string ESIMailBodies {
            get {
                return ResourceManager.GetString("ESIMailBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/mail/lists/.
        /// </summary>
        public static string ESIMailingLists {
            get {
                return ResourceManager.GetString("ESIMailingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/mail/.
        /// </summary>
        public static string ESIMailMessages {
            get {
                return ResourceManager.GetString("ESIMailMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/orders/.
        /// </summary>
        public static string ESIMarketOrders {
            get {
                return ResourceManager.GetString("ESIMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/medals/.
        /// </summary>
        public static string ESIMedals {
            get {
                return ResourceManager.GetString("ESIMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/notifications/.
        /// </summary>
        public static string ESINotifications {
            get {
                return ResourceManager.GetString("ESINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/planets/.
        /// </summary>
        public static string ESIPlanetaryColonies {
            get {
                return ResourceManager.GetString("ESIPlanetaryColonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/characters/{0:D}/planets/{1:D}/.
        /// </summary>
        public static string ESIPlanetaryLayout {
            get {
                return ResourceManager.GetString("ESIPlanetaryLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/universe/planets/{0:D}/.
        /// </summary>
        public static string ESIPlanetInfo {
            get {
                return ResourceManager.GetString("ESIPlanetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/agents_research/.
        /// </summary>
        public static string ESIResearchPoints {
            get {
                return ResourceManager.GetString("ESIResearchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/status/.
        /// </summary>
        public static string ESIServerStatus {
            get {
                return ResourceManager.GetString("ESIServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/ship/.
        /// </summary>
        public static string ESIShip {
            get {
                return ResourceManager.GetString("ESIShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/characters/{0:D}/skillqueue/.
        /// </summary>
        public static string ESISkillQueue {
            get {
                return ResourceManager.GetString("ESISkillQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v4/characters/{0:D}/skills/.
        /// </summary>
        public static string ESISkills {
            get {
                return ResourceManager.GetString("ESISkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/sovereignty/structures/.
        /// </summary>
        public static string ESISovereignty {
            get {
                return ResourceManager.GetString("ESISovereignty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/standings/.
        /// </summary>
        public static string ESIStandings {
            get {
                return ResourceManager.GetString("ESIStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/universe/stations/{0}/.
        /// </summary>
        public static string ESIStationInfo {
            get {
                return ResourceManager.GetString("ESIStationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.testeveonline.com.
        /// </summary>
        public static string ESITestBase {
            get {
                return ResourceManager.GetString("ESITestBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v2/universe/names/.
        /// </summary>
        public static string ESITypeName {
            get {
                return ResourceManager.GetString("ESITypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/characters/{0:D}/calendar/{1:D}/.
        /// </summary>
        public static string ESIUpcomingCalendarEventDetails {
            get {
                return ResourceManager.GetString("ESIUpcomingCalendarEventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/calendar/.
        /// </summary>
        public static string ESIUpcomingCalendarEvents {
            get {
                return ResourceManager.GetString("ESIUpcomingCalendarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v4/characters/{0:D}/wallet/journal/.
        /// </summary>
        public static string ESIWalletJournal {
            get {
                return ResourceManager.GetString("ESIWalletJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1/characters/{0:D}/wallet/transactions/.
        /// </summary>
        public static string ESIWalletTransactions {
            get {
                return ResourceManager.GetString("ESIWalletTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://community.eveonline.com.
        /// </summary>
        public static string EVECommunityBase {
            get {
                return ResourceManager.GetString("EVECommunityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/Flags.xml.
        /// </summary>
        public static string EveFlags {
            get {
                return ResourceManager.GetString("EveFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Alliance/{0}.
        /// </summary>
        public static string EVEGateAllianceProfile {
            get {
                return ResourceManager.GetString("EVEGateAllianceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gate.eveonline.com.
        /// </summary>
        public static string EVEGateBase {
            get {
                return ResourceManager.GetString("EVEGateBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        public static string EVEGateCharacterProfile {
            get {
                return ResourceManager.GetString("EVEGateCharacterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Corporation/{0}.
        /// </summary>
        public static string EVEGateCorporationProfile {
            get {
                return ResourceManager.GetString("EVEGateCorporationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeForward/{0}.
        /// </summary>
        public static string EVEGateMailForward {
            get {
                return ResourceManager.GetString("EVEGateMailForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ReadMessage/{0}.
        /// </summary>
        public static string EVEGateMailOpen {
            get {
                return ResourceManager.GetString("EVEGateMailOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeReply/{0}.
        /// </summary>
        public static string EVEGateMailReply {
            get {
                return ResourceManager.GetString("EVEGateMailReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Mail/ComposeReplyAll/{0}.
        /// </summary>
        public static string EVEGateMailReplyAll {
            get {
                return ResourceManager.GetString("EVEGateMailReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://image.eveonline.com.
        /// </summary>
        public static string EVEImageServerBase {
            get {
                return ResourceManager.GetString("EVEImageServerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://imageserver.eveonline.com.
        /// </summary>
        public static string EVEImageServerCDN {
            get {
                return ResourceManager.GetString("EVEImageServerCDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item_prices2.xml?char_name=evemon&amp;buysell=a.
        /// </summary>
        public static string EVEMarketDataAPIItemPrices {
            get {
                return ResourceManager.GetString("EVEMarketDataAPIItemPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.eve-marketdata.com.
        /// </summary>
        public static string EVEMarketDataBaseUrl {
            get {
                return ResourceManager.GetString("EVEMarketDataBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ec/marketstat.
        /// </summary>
        public static string EVEMarketerAPIItemPrices {
            get {
                return ResourceManager.GetString("EVEMarketerAPIItemPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.evemarketer.com.
        /// </summary>
        public static string EVEMarketerBaseUrl {
            get {
                return ResourceManager.GetString("EVEMarketerBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forums.eveonline.com/t/evemon-4-0-beta-under-new-ownership-conversion-for-esi/75953.
        /// </summary>
        public static string EVEMonForums {
            get {
                return ResourceManager.GetString("EVEMonForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://evemondevteam.github.io/evemon/.
        /// </summary>
        public static string EVEMonMainPage {
            get {
                return ResourceManager.GetString("EVEMonMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://evemon.readthedocs.org/.
        /// </summary>
        public static string EVEMonManual {
            get {
                return ResourceManager.GetString("EVEMonManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/evemon.
        /// </summary>
        public static string EVEMonTwitter {
            get {
                return ResourceManager.GetString("EVEMonTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /updates/patch.xml.
        /// </summary>
        public static string EVEMonUpdates {
            get {
                return ResourceManager.GetString("EVEMonUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/peterhaneve/evemon/issues/.
        /// </summary>
        public static string EVEMonUserVoice {
            get {
                return ResourceManager.GetString("EVEMonUserVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/ExternalEveNotificationTextParser.cs.
        /// </summary>
        public static string ExternalEveNotificationTextParser {
            get {
                return ResourceManager.GetString("ExternalEveNotificationTextParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forums.eveonline.com/t/evemon-4-0-beta-under-new-ownership-conversion-for-esi/75953.
        /// </summary>
        public static string ForumThreadBase {
            get {
                return ResourceManager.GetString("ForumThreadBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/peterhaneve/evemon/master.
        /// </summary>
        public static string GitHubBase {
            get {
                return ResourceManager.GetString("GitHubBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/peterhaneve/evemon/releases.
        /// </summary>
        public static string GitHubDownloadsBase {
            get {
                return ResourceManager.GetString("GitHubDownloadsBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.pool.ntp.org.
        /// </summary>
        public static string GlobalNTPPool {
            get {
                return ResourceManager.GetString("GlobalNTPPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ssl.google-analytics.com/collect.
        /// </summary>
        public static string GoogleAnalyticsUrl {
            get {
                return ResourceManager.GetString("GoogleAnalyticsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=google%20calendar%20get%20calendar%20id.
        /// </summary>
        public static string GoogleCalendarSetup {
            get {
                return ResourceManager.GetString("GoogleCalendarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stop.hammerti.me.uk/api/citadel/{0:D}.
        /// </summary>
        public static string HammertimeCitadel {
            get {
                return ResourceManager.GetString("HammertimeCitadel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /bitmaps/character/level.
        /// </summary>
        public static string MyEVELevelImage {
            get {
                return ResourceManager.GetString("MyEVELevelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tcp://time.nist.gov:13.
        /// </summary>
        public static string NISTTimeServer {
            get {
                return ResourceManager.GetString("NISTTimeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/NotificationRefTypes.xml.
        /// </summary>
        public static string NotificationRefTypes {
            get {
                return ResourceManager.GetString("NotificationRefTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://o.smium.org.
        /// </summary>
        public static string OsmiumBaseUrl {
            get {
                return ResourceManager.GetString("OsmiumBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/convert/{0}/eft.
        /// </summary>
        public static string OsmiumLoadoutDetails {
            get {
                return ResourceManager.GetString("OsmiumLoadoutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/json/loadout/query/{0}?limit=50&amp;sortby=creationdate.
        /// </summary>
        public static string OsmiumLoadoutFeed {
            get {
                return ResourceManager.GetString("OsmiumLoadoutFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /loadout/{0}.
        /// </summary>
        public static string OsmiumLoadoutTopic {
            get {
                return ResourceManager.GetString("OsmiumLoadoutTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type=authorization_code&amp;code={0}&amp;client_id={1}&amp;code_verifier={2}.
        /// </summary>
        public static string PostDataAuthPKCE {
            get {
                return ResourceManager.GetString("PostDataAuthPKCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type=authorization_code&amp;code={0}.
        /// </summary>
        public static string PostDataAuthToken {
            get {
                return ResourceManager.GetString("PostDataAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type=refresh_token&amp;client_id={1}&amp;refresh_token={0}.
        /// </summary>
        public static string PostDataRefreshPKCE {
            get {
                return ResourceManager.GetString("PostDataRefreshPKCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type=refresh_token&amp;refresh_token={0}.
        /// </summary>
        public static string PostDataRefreshToken {
            get {
                return ResourceManager.GetString("PostDataRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/oauth/.
        /// </summary>
        public static string SSOBase {
            get {
                return ResourceManager.GetString("SSOBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/v2/oauth/.
        /// </summary>
        public static string SSOBaseV2 {
            get {
                return ResourceManager.GetString("SSOBaseV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        public static string SSOCharID {
            get {
                return ResourceManager.GetString("SSOCharID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05153596dde44fd8b0d60c0ad3b90c24.
        /// </summary>
        public static string SSODefaultAppID {
            get {
                return ResourceManager.GetString("SSODefaultAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorize/?response_type=code&amp;redirect_uri={0}&amp;client_id={3}&amp;scope={2}&amp;state={1}.
        /// </summary>
        public static string SSOLogin {
            get {
                return ResourceManager.GetString("SSOLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorize/?response_type=code&amp;redirect_uri={0}&amp;client_id={3}&amp;scope={2}&amp;state={1}&amp;code_challenge_method=S256&amp;code_challenge={4}.
        /// </summary>
        public static string SSOLoginPKCE {
            get {
                return ResourceManager.GetString("SSOLoginPKCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:{0:D}/callback.
        /// </summary>
        public static string SSORedirect {
            get {
                return ResourceManager.GetString("SSORedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esi-wallet.read_character_wallet.v1 esi-calendar.read_calendar_events.v1 esi-location.read_location.v1 esi-location.read_ship_type.v1 esi-mail.read_mail.v1 esi-skills.read_skills.v1 esi-skills.read_skillqueue.v1 esi-clones.read_clones.v1 esi-characters.read_contacts.v1 esi-universe.read_structures.v1 esi-killmails.read_killmails.v1 esi-assets.read_assets.v1 esi-planets.manage_planets.v1 esi-markets.structure_markets.v1 esi-corporations.read_structures.v1 esi-characters.read_loyalty.v1 esi-characters.read_me [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SSOScopes {
            get {
                return ResourceManager.GetString("SSOScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string SSOToken {
            get {
                return ResourceManager.GetString("SSOToken", resourceCulture);
            }
        }
    }
}
