//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AccountWide32 {
            get {
                object obj = ResourceManager.GetObject("AccountWide32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BadStanding {
            get {
                object obj = ResourceManager.GetObject("BadStanding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bug {
            get {
                object obj = ResourceManager.GetObject("Bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Error&lt;/title&gt;
        ///    &lt;style&gt;
        ///        p, body { color: #FFFFFF; font-family: ProximaNova-Regular, Arial }
        ///		h2 { text-align: center; margin-bottom: 10px; text-shadow: 1px 1px 2px #7F7F7F; font-size: 30px; font-family: &quot;ProximaNova-SemiBold&quot;,Arial }
        ///        body { background: #000000 url(https://login.eveonline.com/Images/site-bg.jpg) no-repeat center center fixed }
        ///        #content { bac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CallbackFail {
            get {
                return ResourceManager.GetString("CallbackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Authentication Successful&lt;/title&gt;
        ///    &lt;style&gt;
        ///        p, body { color: #FFFFFF; font-family: ProximaNova-Regular, Arial }
        ///		h2 { text-align: center; margin-bottom: 10px; text-shadow: 1px 1px 2px #7F7F7F; font-size: 30px; font-family: &quot;ProximaNova-SemiBold&quot;,Arial }
        ///        body { background: #000000 url(https://login.eveonline.com/Images/site-bg.jpg) no-repeat center center fixed }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CallbackOK {
            get {
                return ResourceManager.GetString("CallbackOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factionID,factionName,description,raceIDs,solarSystemID,corporationID,sizeFactor,stationCount,stationSystemCount,militiaCorporationID,iconID
        ///500001,Caldari State,&quot;The Caldari State is ruled by several mega-corporations. There is no central government to speak of - all territories within the State are owned and ruled by corporations. Duty and discipline are required traits in Caldari citizens, plus unquestioning loyalty to the corporation they live to serve. The corporations compete aggressively amongst the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string chrFactions {
            get {
                return ResourceManager.GetString("chrFactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ContextMenuPointer {
            get {
                object obj = ResourceManager.GetObject("ContextMenuPointer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CrossBlack {
            get {
                object obj = ResourceManager.GetObject("CrossBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CrossGray {
            get {
                object obj = ResourceManager.GetObject("CrossGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///                xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot; /&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Renaming root name &apos;blueprints&apos; in blueprints datafile to &apos;bluep [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DatafilesXSLT {
            get {
                return ResourceManager.GetString("DatafilesXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deadspace {
            get {
                object obj = ResourceManager.GetObject("Deadspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultAllianceImage32 {
            get {
                object obj = ResourceManager.GetObject("DefaultAllianceImage32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultCharacterImage32 {
            get {
                object obj = ResourceManager.GetObject("DefaultCharacterImage32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DefaultCorporationImage32 {
            get {
                object obj = ResourceManager.GetObject("DefaultCorporationImage32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Error16 {
            get {
                object obj = ResourceManager.GetObject("Error16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the wallet balance for {0}..
        /// </summary>
        public static string ErrorAccountBalance {
            get {
                return ResourceManager.GetString("ErrorAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the account status for API key {0}..
        /// </summary>
        public static string ErrorAccountStatus {
            get {
                return ResourceManager.GetString("ErrorAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the assets of {0}..
        /// </summary>
        public static string ErrorAssets {
            get {
                return ResourceManager.GetString("ErrorAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the learning attributes of {0}..
        /// </summary>
        public static string ErrorAttributes {
            get {
                return ResourceManager.GetString("ErrorAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining calendar event attendees for {0}..
        /// </summary>
        public static string ErrorCalendarAttendees {
            get {
                return ResourceManager.GetString("ErrorCalendarAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining calendar event details for {0}..
        /// </summary>
        public static string ErrorCalendarDetails {
            get {
                return ResourceManager.GetString("ErrorCalendarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying calendar events for {0}..
        /// </summary>
        public static string ErrorCalendarEvents {
            get {
                return ResourceManager.GetString("ErrorCalendarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving character list for {0:D}.
        ///If you changed your password, you must log in again using File &gt; Add Character..
        /// </summary>
        public static string ErrorCharacterList {
            get {
                return ResourceManager.GetString("ErrorCharacterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the character sheet for {0}..
        /// </summary>
        public static string ErrorCharacterSheet {
            get {
                return ResourceManager.GetString("ErrorCharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying contacts for {0}..
        /// </summary>
        public static string ErrorContacts {
            get {
                return ResourceManager.GetString("ErrorContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining contract bids for {0}..
        /// </summary>
        public static string ErrorContractBids {
            get {
                return ResourceManager.GetString("ErrorContractBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining contract items for {0}..
        /// </summary>
        public static string ErrorContractItems {
            get {
                return ResourceManager.GetString("ErrorContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the contracts of {0}..
        /// </summary>
        public static string ErrorContracts {
            get {
                return ResourceManager.GetString("ErrorContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the employment history of {0}..
        /// </summary>
        public static string ErrorEmploymentHistory {
            get {
                return ResourceManager.GetString("ErrorEmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the EVE faction war list..
        /// </summary>
        public static string ErrorEVEFacWarList {
            get {
                return ResourceManager.GetString("ErrorEVEFacWarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying EVE factional warfare statistics..
        /// </summary>
        public static string ErrorEVEFacWarStat {
            get {
                return ResourceManager.GetString("ErrorEVEFacWarStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying mail messages for {0}..
        /// </summary>
        public static string ErrorEVEMail {
            get {
                return ResourceManager.GetString("ErrorEVEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining mail contents for {0}..
        /// </summary>
        public static string ErrorEVEMailBody {
            get {
                return ResourceManager.GetString("ErrorEVEMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying mailing lists for {0}..
        /// </summary>
        public static string ErrorEVEMailLists {
            get {
                return ResourceManager.GetString("ErrorEVEMailLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the faction warfare statistics of {0}..
        /// </summary>
        public static string ErrorFacWarStat {
            get {
                return ResourceManager.GetString("ErrorFacWarStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error looking up character identities..
        /// </summary>
        public static string ErrorIDToName {
            get {
                return ResourceManager.GetString("ErrorIDToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the implants of {0}..
        /// </summary>
        public static string ErrorImplants {
            get {
                return ResourceManager.GetString("ErrorImplants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying industry jobs for {0}..
        /// </summary>
        public static string ErrorIndustryJobs {
            get {
                return ResourceManager.GetString("ErrorIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the jump clones of {0}..
        /// </summary>
        public static string ErrorJumpClones {
            get {
                return ResourceManager.GetString("ErrorJumpClones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the jump fatigue of {0}..
        /// </summary>
        public static string ErrorJumpFatigue {
            get {
                return ResourceManager.GetString("ErrorJumpFatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying kill log for {0}..
        /// </summary>
        public static string ErrorKillLog {
            get {
                return ResourceManager.GetString("ErrorKillLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining kill mail {0} from the server..
        /// </summary>
        public static string ErrorKillMail {
            get {
                return ResourceManager.GetString("ErrorKillMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the location of {0}..
        /// </summary>
        public static string ErrorLocation {
            get {
                return ResourceManager.GetString("ErrorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the market orders of {0}..
        /// </summary>
        public static string ErrorMarketOrders {
            get {
                return ResourceManager.GetString("ErrorMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying medals for {0}..
        /// </summary>
        public static string ErrorMedals {
            get {
                return ResourceManager.GetString("ErrorMedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying EVE notifications for {0}..
        /// </summary>
        public static string ErrorNotifications {
            get {
                return ResourceManager.GetString("ErrorNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining planetary production layout for {0}..
        /// </summary>
        public static string ErrorPlanetLayout {
            get {
                return ResourceManager.GetString("ErrorPlanetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying planetary production information..
        /// </summary>
        public static string ErrorPlanets {
            get {
                return ResourceManager.GetString("ErrorPlanets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying research points for {0}..
        /// </summary>
        public static string ErrorResearchPoints {
            get {
                return ResourceManager.GetString("ErrorResearchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the current ship of {0}..
        /// </summary>
        public static string ErrorShip {
            get {
                return ResourceManager.GetString("ErrorShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erorr querying the skill queue of {0}..
        /// </summary>
        public static string ErrorSkillQueue {
            get {
                return ResourceManager.GetString("ErrorSkillQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the known skills of {0}..
        /// </summary>
        public static string ErrorSkills {
            get {
                return ResourceManager.GetString("ErrorSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in to EVE SSO.
        ///If you changed your password, you must log in again using File &gt; Add Character..
        /// </summary>
        public static string ErrorSSO {
            get {
                return ResourceManager.GetString("ErrorSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the standings of {0}..
        /// </summary>
        public static string ErrorStandings {
            get {
                return ResourceManager.GetString("ErrorStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error looking up station information..
        /// </summary>
        public static string ErrorStation {
            get {
                return ResourceManager.GetString("ErrorStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying the EVE server status. Check EVE server uptime on http://eve-offline.net/.
        /// </summary>
        public static string ErrorStatus {
            get {
                return ResourceManager.GetString("ErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error looking up citadel information..
        /// </summary>
        public static string ErrorStructure {
            get {
                return ResourceManager.GetString("ErrorStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying wallet journal for {0}..
        /// </summary>
        public static string ErrorWalletJournal {
            get {
                return ResourceManager.GetString("ErrorWalletJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error querying wallet transactions for {0}..
        /// </summary>
        public static string ErrorWalletTransactions {
            get {
                return ResourceManager.GetString("ErrorWalletTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon EVEMon {
            get {
                object obj = ResourceManager.GetObject("EVEMon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExcellentStanding {
            get {
                object obj = ResourceManager.GetObject("ExcellentStanding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Faction {
            get {
                object obj = ResourceManager.GetObject("Faction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;invFlags xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;rowset name=&quot;flags&quot; key=&quot;flagID&quot; columns=&quot;flagID,flagName,flagText&quot;&gt;
        ///    &lt;row flagID=&quot;0&quot; flagName=&quot;None&quot; flagText=&quot;None&quot; /&gt;
        ///    &lt;row flagID=&quot;1&quot; flagName=&quot;Wallet&quot; flagText=&quot;Wallet&quot; /&gt;
        ///    &lt;row flagID=&quot;2&quot; flagName=&quot;Offices&quot; flagText=&quot;OfficeFolder&quot; /&gt;
        ///    &lt;row flagID=&quot;3&quot; flagName=&quot;Wardrobe&quot; flagText=&quot;Wardrobe&quot; /&gt;
        ///    &lt;row flagID=&quot;4&quot; flagName=&quot;Hangar&quot; flagText=&quot;Hangar&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GoodStanding {
            get {
                object obj = ResourceManager.GetObject("GoodStanding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Information16 {
            get {
                object obj = ResourceManager.GetObject("Information16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KeyGold16 {
            get {
                object obj = ResourceManager.GetObject("KeyGold16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KeyGrey16 {
            get {
                object obj = ResourceManager.GetObject("KeyGrey16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KeyWrong32 {
            get {
                object obj = ResourceManager.GetObject("KeyWrong32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Medal32 {
            get {
                object obj = ResourceManager.GetObject("Medal32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account expires in {0}: {1}..
        /// </summary>
        public static string MessageExpiration {
            get {
                return ResourceManager.GetString("MessageExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0} has less than {1} day{2} of skills queued..
        /// </summary>
        public static string MessageLessThanDay {
            get {
                return ResourceManager.GetString("MessageLessThanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0} has insufficient funds to fulfill all of its buy orders..
        /// </summary>
        public static string MessageMarginTrading {
            get {
                return ResourceManager.GetString("MessageMarginTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} assigned contract{1}..
        /// </summary>
        public static string MessageNewContracts {
            get {
                return ResourceManager.GetString("MessageNewContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NeutralStanding {
            get {
                object obj = ResourceManager.GetObject("NeutralStanding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;eveapi version=&quot;2&quot;&gt;
        ///  &lt;currentTime&gt;&lt;/currentTime&gt;
        ///  &lt;result&gt;
        ///    &lt;rowset name=&quot;refTypes&quot; key=&quot;refTypeID&quot; columns=&quot;refTypeID,refTypeCode,refTypeName,subjectLayout,textLayout&quot;&gt;
        ///      &lt;row refTypeID=&quot;1&quot; refTypeCode=&quot;OldLscMessages&quot; refTypeName=&quot;Old Notifications&quot; subjectLayout=&quot;{subject}&quot; textLayout=&quot;{body}&quot;/&gt;
        ///      &lt;row refTypeID=&quot;2&quot; refTypeCode=&quot;CharTerminationMsg&quot; refTypeName=&quot;Member Biomassed&quot; subjectLayout=&quot;RIP Corporation member {charID}&quot; textLayout=&quot;The untimely death of fel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationRefTypes {
            get {
                return ResourceManager.GetString("NotificationRefTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Officer {
            get {
                object obj = ResourceManager.GetObject("Officer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;eveapi version=&quot;2&quot;&gt;
        ///  &lt;currentTime&gt;2018-03-27 00:53:15&lt;/currentTime&gt;
        ///  &lt;result&gt;
        ///    &lt;rowset name=&quot;refTypes&quot; key=&quot;refTypeID&quot; columns=&quot;refTypeID,refTypeName&quot;&gt;
        ///      &lt;row refTypeID=&quot;0&quot; refTypeName=&quot;Undefined&quot; /&gt;
        ///      &lt;row refTypeID=&quot;1&quot; refTypeName=&quot;Player Trading&quot; /&gt;
        ///      &lt;row refTypeID=&quot;2&quot; refTypeName=&quot;Market Transaction&quot; /&gt;
        ///      &lt;row refTypeID=&quot;3&quot; refTypeName=&quot;GM Cash Transfer&quot; /&gt;
        ///      &lt;row refTypeID=&quot;4&quot; refTypeName=&quot;ATM Withdraw&quot; /&gt;
        ///      &lt;row refTypeID= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RefTypes {
            get {
                return ResourceManager.GetString("RefTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///                xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot; /&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot; /&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Rowsets are transformed into something else--&gt;
        ///  &lt;xsl:templat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RowsetsXSLT {
            get {
                return ResourceManager.GetString("RowsetsXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot; /&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!--Transforms the SerializableDictionary to its Modified version--&gt;
        ///  &lt;xsl:templa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettingsXSLT {
            get {
                return ResourceManager.GetString("SettingsXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream SkillTrained {
            get {
                return ResourceManager.GetStream("SkillTrained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Storyline {
            get {
                object obj = ResourceManager.GetObject("Storyline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T2 {
            get {
                object obj = ResourceManager.GetObject("T2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap T3 {
            get {
                object obj = ResourceManager.GetObject("T3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TerribleStanding {
            get {
                object obj = ResourceManager.GetObject("TerribleStanding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Throbber {
            get {
                object obj = ResourceManager.GetObject("Throbber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warning16 {
            get {
                object obj = ResourceManager.GetObject("Warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Watch {
            get {
                object obj = ResourceManager.GetObject("Watch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:template match=&quot;outputCharacter&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;
        ///          Character Sheet ::
        ///          &lt;xsl:value-of select=&quot;@name&quot; /&gt;
        ///        &lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;table&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;
        ///              &lt;xsl:element name=&quot;img&quot;&gt;
        ///                &lt;xsl:attribute name=&quot;src&quot;&gt;http://image.eveonline.com/character/&lt;xsl:value-of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XmlToHtmlXslt {
            get {
                return ResourceManager.GetString("XmlToHtmlXslt", resourceCulture);
            }
        }
    }
}
