IF OBJECT_ID('dbo.agtAgentTypes', 'U') IS NOT NULL
DROP TABLE [dbo].[agtAgentTypes]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[agtAgentTypes](
	[agentTypeID] [int] NOT NULL,
	[agentType] [varchar](50) NULL,
 CONSTRAINT [agtAgentTypes_PK] PRIMARY KEY CLUSTERED 
(
	[agentTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF