IF OBJECT_ID('dbo.chrRaces', 'U') IS NOT NULL
DROP TABLE [dbo].[chrRaces]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[chrRaces](
	[raceID] [tinyint] NOT NULL,
	[raceName] [varchar](100) NULL,
	[description] [varchar](1000) NULL,
	[iconID] [int] NULL,
	[shortDescription] [varchar](500) NULL,
 CONSTRAINT [chrRaces_PK] PRIMARY KEY CLUSTERED 
(
	[raceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF