IF OBJECT_ID('dbo.dgmTypeEffects', 'U') IS NOT NULL
DROP TABLE [dbo].[dgmTypeEffects]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[dgmTypeEffects](
	[typeID] [int] NOT NULL,
	[effectID] [smallint] NOT NULL,
	[isDefault] [bit] NULL,
 CONSTRAINT [dgmTypeEffects_PK] PRIMARY KEY CLUSTERED 
(
	[typeID] ASC,
	[effectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]