IF OBJECT_ID('dbo.dgmTypeMasteries', 'U') IS NOT NULL
DROP TABLE [dbo].[dgmTypeMasteries]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[dgmTypeMasteries](
	[typeID] [int] NOT NULL,
	[masteryID] [smallint] NOT NULL,
 CONSTRAINT [dgmTypeMasteries_PK] PRIMARY KEY CLUSTERED 
(
	[typeID] ASC,
	[masteryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]