IF OBJECT_ID('dbo.dgmTraits', 'U') IS NOT NULL
DROP TABLE [dbo].[dgmTraits]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[dgmTraits](
	[traitID] [int] NOT NULL,
	[bonusText] [nvarchar](500) NOT NULL,
	[unitID] [tinyint] NULL,
 CONSTRAINT [dgmTraits_PK] PRIMARY KEY CLUSTERED 
(
	[traitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]