IF OBJECT_ID('dbo.eveUnits', 'U') IS NOT NULL
DROP TABLE [dbo].[eveUnits]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[eveUnits](
	[unitID] [tinyint] NOT NULL,
	[unitName] [varchar](100) NULL,
	[displayName] [varchar](50) NULL,
	[description] [varchar](1000) NULL,
 CONSTRAINT [eveUnits_PK] PRIMARY KEY CLUSTERED 
(
	[unitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF