IF OBJECT_ID('dbo.invFlags', 'U') IS NOT NULL
DROP TABLE [dbo].[invFlags]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[invFlags](
	[flagID] [smallint] NOT NULL,
	[flagName] [varchar](200) NULL,
	[flagText] [varchar](100) NULL,
	[orderID] [int] NULL,
 CONSTRAINT [invFlags_PK] PRIMARY KEY CLUSTERED 
(
	[flagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF