IF OBJECT_ID('dbo.invTypeMaterials', 'U') IS NOT NULL
DROP TABLE [dbo].[invTypeMaterials]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[invTypeMaterials](
	[typeID] [int] NOT NULL,
	[materialTypeID] [int] NOT NULL,
	[quantity] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [invTypeMaterials_PK] PRIMARY KEY CLUSTERED 
(
	[typeID] ASC,
	[materialTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]