IF OBJECT_ID('dbo.mapJumps', 'U') IS NOT NULL
DROP TABLE [dbo].[mapJumps]; 

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[mapJumps](
	[stargateID] [int] NOT NULL,
	[celestialID] [int] NULL,
 CONSTRAINT [mapJumps_PK] PRIMARY KEY CLUSTERED 
(
	[stargateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]