IF OBJECT_ID('dbo.sknLicenses', 'U') IS NOT NULL
DROP TABLE [dbo].[sknLicenses]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[sknLicenses](
	[licenseTypeID] [int] NOT NULL,
	[skinID] [int] NOT NULL,
	[duration] [int] NOT NULL,
 CONSTRAINT [sknLicenses_PK] PRIMARY KEY CLUSTERED 
(
	[licenseTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF

ALTER TABLE [dbo].[sknLicenses] ADD  DEFAULT ((-1)) FOR [duration]