//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.SQLiteToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapDenormalize
    {
        public long itemID { get; set; }
        public Nullable<long> typeID { get; set; }
        public Nullable<long> groupID { get; set; }
        public Nullable<long> solarSystemID { get; set; }
        public Nullable<long> constellationID { get; set; }
        public Nullable<long> regionID { get; set; }
        public Nullable<long> orbitID { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> z { get; set; }
        public Nullable<double> radius { get; set; }
        public string itemName { get; set; }
        public Nullable<double> security { get; set; }
        public Nullable<long> celestialIndex { get; set; }
        public Nullable<long> orbitIndex { get; set; }
    }
}
