//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.SQLiteToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapJumps
    {
        public long stargateID { get; set; }
        public Nullable<long> destinationID { get; set; }
    }
}
