// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1300:SpecifyMessageBoxOptions", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#ShowMessage(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1300:SpecifyMessageBoxOptions", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#SaveFile()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.DateTimePicker.set_CustomFormat(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "EVEMon.PatchXmlCreator.Helper.ShowMessage(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#EnsurePrerequisites()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#SelectAction()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.MessageBox.Show(System.String,System.String,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon)", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#ShowMessage(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.DateTimePicker.set_CustomFormat(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.MessageBox.Show(System.String,System.String,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon)", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#SaveFile()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#UpdateDatafilesMessage()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "battleclinic", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "BattleClinic", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "bitbucket", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Datafiles", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#SelectAction()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "datafiles", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "eve-datafilename-culture-xml", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "EVEMon", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#UpdateDatafilesMessage()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "EVEMon", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "EVEMon", Scope = "member", Target = "EVEMon.PatchXmlCreator.Helper.#EnsurePrerequisites()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "evemon", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "gzip", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "php", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "yyyy", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "yyyy", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "EVEMon.Common.Serialization.PatchXml.SerializableDatafile.set_Message(System.String)", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#ExportDatafiles(System.Collections.Generic.ICollection`1<EVEMon.Common.Serialization.PatchXml.SerializableDatafile>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "dd", Scope = "member", Target = "EVEMon.PatchXmlCreator.DatafileControl.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "EVEMon", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#ExportDatafiles(System.Collections.Generic.ICollection`1<EVEMon.Common.Serialization.PatchXml.SerializableDatafile>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "dd", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Exp", Scope = "member", Target = "EVEMon.PatchXmlCreator.PatchXmlCreatorWindow.#InitializeComponent()")]
